#define IR_UP       1
#define IR_DOWN     2
#define IR_LEFT     4
#define IR_RIGHT    3
#define IR_OK       5
#define IR_1        6
#define IR_2        7
#define IR_3        8
#define IR_4        9
#define IR_5        10
#define IR_6        11
#define IR_7        12
#define IR_8        13
#define IR_9        14
